### PR TITLE
Add timeout to prevent home assistant block on startup when sense is down

### PR DESCRIPTION
**Pull request by bdraco**
This is to address

https://github.com/home-assistant/core/issues/28760

### CODE REVIEW

**Comment by bdraco** [comment]
Testing steps
```
  iptables -A INPUT -s 34.194.131.108 -j DROP
   iptables -A INPUT -s 34.201.233.5 -j DROP
```
Start home assistant and watch it block

**Comment by bdraco** [comment]
```
2020-03-09 23:21:13 WARNING (MainThread) [homeassistant.config_entries] Config entry for sense not ready yet. Retrying in 10 seconds.
2020-03-09 23:21:34 WARNING (MainThread) [homeassistant.config_entries] Config entry for sense not ready yet. Retrying in 20 seconds.
2020-03-09 23:22:05 WARNING (MainThread) [homeassistant.config_entries] Config entry for sense not ready yet. Retrying in 40 seconds.
2020-03-09 23:22:21 DEBUG (MainThread) [custom_components.griddy] Finished fetching Griddy getnow data in 0.299 seconds
2020-03-09 23:22:56 WARNING (MainThread) [homeassistant.config_entries] Config entry for sense not ready yet. Retrying in 80 seconds.

```
Confirmed this fixes it

**Comment by bdraco** [comment]
@kbickar Did I send this PR to the right place?

**Review by kbickar — APPROVED** [review]

**Comment by bdraco** [comment]
@kbickar Can you push out a 0.7.1 so I can get HA updated?

**Comment by bdraco** [comment]
Thanks @kbickar. Taking care of https://github.com/home-assistant/core/issues/28760 now

**Pull request merged**
