### PR TITLE
Allow custom certificate verification

### PR DESCRIPTION
**Pull request by dsbecker**
Allow custom certificate verification when running behind a corporate proxy. See: https://requests.readthedocs.io/en/latest/user/advanced/#ssl-cert-verification

### CODE REVIEW

**Comment by PopRe** [comment]
Please make the change in the async version as well

**Comment by dsbecker** [comment]
@PopRe I made a change that I _**think**_ will do the trick. I'm a total noob to python and only learned just enough to use this API and make my original change. 

I'm not certain how to properly use the async version, but I do not get any errors on when calling the async authenticate method.

I encourage you to sanity check me please!

**Comment by dsbecker** [comment]
I'm not even 100% confident it works reliably in the non-async version. Sometimes when I try to run my script I still get certificate errors, but the second time I run it they work fine (with the fix, without it they never work).

Sorry if this is too sloppy for you to pick up, but it works for me and I just wanted to share.

Make of it what you will.

**Comment by dsbecker** [comment]
> Sometimes when I try to run my script I still get certificate errors, but the second time I run it they work fine.

After a few more days using my changes, the oddities I was seeing only happen right after signing on my work VPN or off it. As if the VPN hasn’t finished setting up the proxy yet. If I wait a minute before running the script everything works fine as expected. So I’m pretty sure these changes are working as intended.

**Comment by dsbecker** [comment]
I’ve also found that just setting this environment variable will do the trick in Python < 3, but not in Python 3.

https://www.prado.lt/how-to-fix-python-ssl-certificate_verify_failed

**Comment by dsbecker** [comment]
I cleaned this up a bit to add support for a simple bool flag to just disable cert verification while also allowing use of custom certificate files if desired.

**Comment by kbickar** [comment]
Maybe add another argument for a cafile so ssl_verify isn't being used for two purposes

**Comment by dsbecker** [comment]
Originally I was just using verify because that’s what the option was called in requests and since it serves double duty there I thought I’d do the same. But then in the async version it’s not called that and there’s different ways of doing it. So I thought I’d rename it to ssl_verify for both to be consistent and also to make it more clear since it might not be clear on the authenticate call what verify meant. But I didn’t think about splitting it into two parameters. That makes sense and would make the if statements more clear.

**Comment by dsbecker** [comment]
@kbickar Changes made. Thanks for the suggestion!

**Comment by dsbecker** [comment]
@kbickar Very nice, thank you. Sorry for my python style ignorance... :)

**Pull request merged**
